// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxFdpwZ8xVKKxVABuYX_8Mtuz1BqESTEo',
    appId: '1:334096525:web:b4fa74500e1611902edac4',
    messagingSenderId: '334096525',
    projectId: 'tennisreminder-ecf66',
    authDomain: 'tennisreminder-ecf66.firebaseapp.com',
    storageBucket: 'tennisreminder-ecf66.firebasestorage.app',
    measurementId: 'G-DGVXR4RSG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgITAhBu0-Ttbf0sz7BgfGm2H-ywg6OBw',
    appId: '1:334096525:android:2e5078088825f0522edac4',
    messagingSenderId: '334096525',
    projectId: 'tennisreminder-ecf66',
    storageBucket: 'tennisreminder-ecf66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4AGKpBPYL20oLTjxAO8OWWN2KWb4xsg',
    appId: '1:334096525:ios:7ad4af2c35500e242edac4',
    messagingSenderId: '334096525',
    projectId: 'tennisreminder-ecf66',
    storageBucket: 'tennisreminder-ecf66.firebasestorage.app',
    androidClientId: '334096525-rrm2ft4g83lbhun79qmrkbgs2v2pb0hf.apps.googleusercontent.com',
    iosClientId: '334096525-o7v0fsdf329k9875h2k3cidrkd3oo965.apps.googleusercontent.com',
    iosBundleId: 'com.example.tennisReminderAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC4AGKpBPYL20oLTjxAO8OWWN2KWb4xsg',
    appId: '1:334096525:ios:7ad4af2c35500e242edac4',
    messagingSenderId: '334096525',
    projectId: 'tennisreminder-ecf66',
    storageBucket: 'tennisreminder-ecf66.firebasestorage.app',
    androidClientId: '334096525-rrm2ft4g83lbhun79qmrkbgs2v2pb0hf.apps.googleusercontent.com',
    iosClientId: '334096525-o7v0fsdf329k9875h2k3cidrkd3oo965.apps.googleusercontent.com',
    iosBundleId: 'com.example.tennisReminderAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxFdpwZ8xVKKxVABuYX_8Mtuz1BqESTEo',
    appId: '1:334096525:web:3dfd4818d9cdaf132edac4',
    messagingSenderId: '334096525',
    projectId: 'tennisreminder-ecf66',
    authDomain: 'tennisreminder-ecf66.firebaseapp.com',
    storageBucket: 'tennisreminder-ecf66.firebasestorage.app',
    measurementId: 'G-Z70Y7WG3YH',
  );

}