// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5XgdALLiLCT9Ld9P7JNW5JUqgqxEPEyc',
    appId: '1:844563512875:web:13e0d96073db71b16ab46e',
    messagingSenderId: '844563512875',
    projectId: 'clothes-fc9f2',
    authDomain: 'clothes-fc9f2.firebaseapp.com',
    storageBucket: 'clothes-fc9f2.firebasestorage.app',
    measurementId: 'G-FSWZDQ2FGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5zLCzw0smtI3d0jzgoqsfVRPZMaM-iE',
    appId: '1:844563512875:android:d32b7d434c1c10d86ab46e',
    messagingSenderId: '844563512875',
    projectId: 'clothes-fc9f2',
    storageBucket: 'clothes-fc9f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcTwD-h-RgTiTsu2GJfx0MZQHYTS8Qs_I',
    appId: '1:844563512875:ios:e68ae8d86c97712e6ab46e',
    messagingSenderId: '844563512875',
    projectId: 'clothes-fc9f2',
    storageBucket: 'clothes-fc9f2.firebasestorage.app',
    iosBundleId: 'com.example.tennisReminderAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcTwD-h-RgTiTsu2GJfx0MZQHYTS8Qs_I',
    appId: '1:844563512875:ios:e68ae8d86c97712e6ab46e',
    messagingSenderId: '844563512875',
    projectId: 'clothes-fc9f2',
    storageBucket: 'clothes-fc9f2.firebasestorage.app',
    iosBundleId: 'com.example.tennisReminderAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5XgdALLiLCT9Ld9P7JNW5JUqgqxEPEyc',
    appId: '1:844563512875:web:a4498d5fd9ea5e2f6ab46e',
    messagingSenderId: '844563512875',
    projectId: 'clothes-fc9f2',
    authDomain: 'clothes-fc9f2.firebaseapp.com',
    storageBucket: 'clothes-fc9f2.firebasestorage.app',
    measurementId: 'G-1M46T97DL0',
  );
}
